// src/lib/data.ts -- REFINED WITH CASE STUDY FORMAT

export const projectsData = [
  {
    id: 1,
    title: "Genius Mart",
    tagline: "High-Performance E-commerce Platform",
    description: "The challenge was to build a premium online grocery store for the Pakistani market that felt as fast and responsive as a native app, even on slower networks. The solution involved a server-first architecture using Next.js, resulting in an ultra-fast, PWA-ready platform with a 95+ Lighthouse score, built from scratch in 26 days.",
    features: [
      "Robust Google OAuth Authentication",
      "Instant Live Search (<300ms)",
      "Dynamic Shopping Cart & Wishlist",
      "Secure Paymob Payment Gateway",
      "Comprehensive User Dashboard",
      "Fully Responsive PWA Design",
    ],
    stack: [
      "Next.js 15",
      "React 19",
      "SCSS Modules",
      "Supabase",
      "Vercel",
      "Cloudinary",
    ],
    image: "/projects/genius-mart-display.png",
    liveSiteUrl: "https://geniusmart.vercel.app/",
  },
  {
    id: 2,
    title: "Genius Mart Admin Portal",
    tagline: "Enterprise-Grade Backend Management System",
    description: "Standard e-commerce backends are often slow and clunky. I engineered a custom, blazing-fast admin portal with a hyper-granular, per-user permission system. The outcome is an intuitive, secure, and highly efficient interface that allows for enterprise-grade management of products, orders, and users.",
    features: [
      "Real-time Analytics Dashboard",
      "Granular, Per-User Permission System",
      "Dynamic, Action-Based UI",
      "Professional PDF Invoice Generation",
      "Row Level Security (RLS) Policies",
      "Custom PL/pgSQL Database Functions",
    ],
    stack: [
      "Next.js 15",
      "React 18",
      "TypeScript",
      "Supabase",
      "Ant Design 5",
      "Zustand",
    ],
    image: "/projects/admin-portal-display.png",
    // No live site URL for admin portals
  },
  {
    id: 3,
    title: "AJ Collections",
    tagline: "Bespoke E-commerce for Fine Accessories",
    description: "The goal was to create a digital storefront that mirrored the elegance of the jewelry itself. By building a custom Next.js application from the ground up, I delivered a highly attractive and performant user experience, focusing on visual fidelity and a seamless, secure checkout flow to drive conversions.",
    features: [
      "Advanced Image Zoom & Product Gallery",
      "Secure Multi-Step Checkout Flow",
      "Personalized User Accounts",
      "Dynamic Filtering by Category & Material",
      "Optimized for Core Web Vitals",
      "Custom Admin Inventory Management",
    ],
    stack: [
      "Next.js",
      "TypeScript",
      "Sass/SCSS",
      "PostgreSQL",
      "Supabase Auth",
      "Supabase Storage",
    ],
    image: "/projects/ajcollections-display.png",
    liveSiteUrl: "https://ajcollections.vercel.app/",
  },
];